#!/usr/bin/env python3
"""
sarthi-snow MCP stdio server — ServiceNow CRQ tools for sArthI.

Ports snow_client.py REST logic into MCP tools. No browser automation —
add_approver_via_browser stays in snow_client.py CLI only.

Tools:
  get_crq               — GET a change request by CHG number
  create_crq_draft      — POST a new CRQ in Draft state (state=-5, never submits)
  parse_crq_file        — Parse a .txt CRQ file into ServiceNow field dict
  search_incidents      — Search incidents by assignment group + state (default: from team-config.yaml)
  get_incident          — GET an incident by INC number (full details, display names not GUIDs)
  get_my_ritm_approvals — Get RITM approvals pending for the current user (sysapproval_approver)

Session auth:
  Reads ~/.wibey/snow-session.json (generated by extract_snow_session.py).
  On 401 → returns session_expired error, does NOT auto-refresh.

CRITICAL: stdout is JSON-RPC. ALL diagnostic output → sys.stderr. NEVER use print() to stdout.
"""

import sys
import os
import json
import re
import argparse
from datetime import datetime, timedelta, timezone
from pathlib import Path
from http.client import HTTPSConnection
from urllib.parse import urlparse
import urllib.request

# ── stderr logger ─────────────────────────────────────────────────────────────
def log(*args, **kwargs):
    print(*args, **kwargs, file=sys.stderr, flush=True)

# ── Team config loader ────────────────────────────────────────────────────────
TEAM_CONFIG_PATH = Path(os.environ.get(
    "SARTHI_TEAM_CONFIG",
    Path.home() / "sarthi" / "knowledge" / "team-config.yaml"
))

def _load_team_config() -> dict:
    """Load team-config.yaml. Returns {} if not found (tools use hardcoded fallbacks)."""
    if not TEAM_CONFIG_PATH.exists():
        return {}
    try:
        import yaml
        with open(TEAM_CONFIG_PATH) as f:
            return yaml.safe_load(f) or {}
    except ImportError:
        # pyyaml unavailable — basic key:value parse for snow section only
        try:
            result = {}
            with open(TEAM_CONFIG_PATH) as f:
                in_snow = False
                for line in f:
                    stripped = line.strip()
                    if stripped == "servicenow:":
                        in_snow = True
                        continue
                    if in_snow:
                        if stripped and not stripped.startswith("#") and ":" in stripped and not stripped.startswith(" "):
                            break  # new top-level section
                        if stripped and not stripped.startswith("#") and ":" in stripped:
                            k, _, v = stripped.partition(":")
                            result[k.strip()] = v.strip().strip('"')
            return {"servicenow": result} if result else {}
        except Exception:
            return {}
    except Exception as e:
        log(f"WARN: could not load team-config: {e}")
        return {}

def _snow_defaults() -> dict:
    """Get ServiceNow field defaults from team-config, falling back to built-in values."""
    cfg = _load_team_config()
    snow = cfg.get("servicenow", {})
    return {
        "assignment_group":           snow.get("assignment_group",           "INTL-ET360"),
        "primary_escalation_group":   snow.get("primary_escalation_group",   "INTL-ET360"),
        "secondary_escalation_group": snow.get("secondary_escalation_group", "INTL-ET360"),
        "change_manager_group":       snow.get("change_manager_group",       "Change Managers - US"),
        "cmdb_ci":                    snow.get("cmdb_ci",                    "International Datalake"),
        "affected_application":       snow.get("affected_application",       "International Datalake"),
        "market":                     snow.get("market",                     "Home Office"),
    }


# ── Constants ─────────────────────────────────────────────────────────────────
SERVICENOW_BASE = "https://walmartglobal.service-now.com"
CHANGE_REQUEST_TABLE = "/api/now/table/change_request"
INCIDENT_TABLE = "/api/now/table/incident"
SESSION_FILE = Path.home() / ".wibey" / "snow-session.json"
TIMEOUT = 20

# Field mapping: friendly names → ServiceNow API field names
FIELD_MAP = {
    "short_description": "short_description",
    "description": "description",
    "risk": "risk",
    "impact": "impact",
    "type": "type",
    "category": "category",
    "state": "state",
    "change_owner_group": "assignment_group",
    "impacted_geos": "u_impacted_geo",
    "business_unit": "u_business_unit",
    "reason_for_install": "u_reason_for_install",
    "affected_application": "u_affected_application",
    "primary_ci": "cmdb_ci",
    "dr_tier": "u_dr_tier",
    "change_classification": "u_change_classification",
    "has_testing_completed": "u_has_testing_completed",
    "type_of_testing": "u_type_of_testing",
    "implementation_plan": "u_implementation_plan",
    "validation_plan": "u_validation_plan",
    "backout_plan": "u_backout_plan",
    "cab_required": "cab_required",
}

STATE_DRAFT = "-5"


# ── Session loader ────────────────────────────────────────────────────────────
def load_session() -> dict | None:
    if not SESSION_FILE.exists():
        return None
    try:
        with open(SESSION_FILE) as f:
            return json.load(f)
    except Exception as e:
        log(f"WARN: Cannot read {SESSION_FILE}: {e}")
        return None


def session_expired_error() -> dict:
    return {
        "error": "session_expired",
        "message": "ServiceNow session cookie expired or missing.",
        "fix": "ServiceNow session expired. Use sarthi-snow-auth MCP: call refresh_session tool, or run: python3 ~/sarthi/scripts/crq/extract_snow_session.py",
    }


# ── HTTP helpers ──────────────────────────────────────────────────────────────
def _http(method: str, path_with_query: str, headers: dict, body: dict | None = None) -> tuple[int, dict | str]:
    """Low-level HTTPS request via system proxy. Returns (status, parsed_json_or_raw_str)."""
    try:
        url = f"{SERVICENOW_BASE}{path_with_query}"
        body_bytes = json.dumps(body).encode() if body is not None else None
        req = urllib.request.Request(url, data=body_bytes, headers=headers, method=method)
        # urllib.request honours https_proxy / HTTPS_PROXY env vars automatically
        proxy_handler = urllib.request.ProxyHandler()
        opener = urllib.request.build_opener(proxy_handler)
        with opener.open(req, timeout=TIMEOUT) as resp:
            raw = resp.read().decode("utf-8", errors="replace")
            token = resp.headers.get("X-UserToken-Response", "")
            try:
                return resp.status, json.loads(raw), token
            except json.JSONDecodeError:
                return resp.status, {"_raw": raw}, token
    except urllib.error.HTTPError as e:
        raw = e.read().decode("utf-8", errors="replace")
        token = e.headers.get("X-UserToken-Response", "")
        try:
            return e.code, json.loads(raw), token
        except json.JSONDecodeError:
            return e.code, {"_raw": raw}, token
    except Exception as e:
        return None, str(e), ""


def _get_user_token(session: dict) -> str:
    """Obtain X-UserToken by making a lightweight GET. Caches in session dict."""
    if session.get("x_user_token"):
        return session["x_user_token"]
    headers = {
        "Cookie": session.get("cookie_header", ""),
        "Accept": "application/json",
    }
    path = f"{CHANGE_REQUEST_TABLE}?sysparm_limit=1&sysparm_fields=number"
    status, _, token = _http("GET", path, headers)
    if token:
        session["x_user_token"] = token
    return token


def _build_headers(session: dict) -> dict:
    token = _get_user_token(session)
    return {
        "Cookie": session.get("cookie_header", ""),
        "Content-Type": "application/json",
        "Accept": "application/json",
        "X-UserToken": token,
    }


# ── Tool implementations ──────────────────────────────────────────────────────

def tool_get_crq(args: dict) -> dict:
    """
    GET a ServiceNow change request by CHG number.

    Args:
      number       (str, required) — e.g. "CHG3978198"
      show_all_fields (bool, default false) — if true, returns all raw fields
    """
    number = args.get("number", "").strip()
    if not number:
        return {"error": "number is required"}
    show_all = bool(args.get("show_all_fields", False))

    session = load_session()
    if not session:
        return session_expired_error()

    headers = _build_headers(session)
    query = f"number={number}"
    params = f"sysparm_query={query}&sysparm_limit=1"
    if not show_all:
        # Return a curated set of useful fields
        fields = ",".join([
            "number", "sys_id", "short_description", "state", "risk", "impact",
            "type", "category", "assignment_group", "cmdb_ci", "cab_required",
            "description", "u_implementation_plan", "u_validation_plan",
            "u_backout_plan", "start_date", "end_date", "opened_at",
            "u_affected_application", "u_change_classification",
        ])
        params += f"&sysparm_fields={fields}"

    path = f"{CHANGE_REQUEST_TABLE}?{params}"
    status, data, _ = _http("GET", path, headers)

    if status is None:
        return {"error": "connection_failed", "detail": str(data)}
    if status == 401:
        return session_expired_error()
    if status != 200:
        return {"error": f"http_{status}", "detail": str(data)[:500]}

    records = data.get("result", [])
    if not records:
        return {"error": "not_found", "number": number}

    record = records[0]
    # Flatten display_value from reference fields
    result = {}
    for k, v in record.items():
        if isinstance(v, dict):
            result[k] = v.get("display_value") or v.get("value") or ""
        else:
            result[k] = v

    return {"crq": result}


def tool_parse_crq_file(args: dict) -> dict:
    """
    Parse a .txt CRQ file (format from /crq-generator skill) into ServiceNow fields.
    Returns the field dict ready to pass to create_crq_draft.

    Args:
      path (str, required) — path to the .txt file (~ expansion supported)
    """
    path_str = args.get("path", "").strip()
    if not path_str:
        return {"error": "path is required"}

    path = Path(path_str).expanduser()
    if not path.exists():
        return {"error": "file_not_found", "path": str(path)}

    try:
        text = path.read_text()
    except Exception as e:
        return {"error": "read_failed", "detail": str(e)}

    lines = text.splitlines()
    fields: dict = {}
    current_section = None
    section_buffer: list[str] = []

    def flush_section():
        nonlocal section_buffer
        content = "\n".join(section_buffer).strip()
        if current_section == "summary":
            fields["short_description"] = content
        elif current_section == "description":
            fields["description"] = content
        elif current_section == "implementation":
            fields["u_implementation_plan"] = content
        elif current_section == "validation":
            fields["u_validation_plan"] = content
        elif current_section == "backout":
            fields["u_backout_plan"] = content
        section_buffer.clear()

    SECTION_MARKERS = {
        "Summary": "summary",
        "Description": "description",
        "Implementation plan": "implementation",
        "Validation plan": "validation",
        "Backout plan": "backout",
    }
    SEPARATOR_RE = re.compile(r"^[─\-]{5,}")

    meta: dict = {}
    for line in lines:
        stripped = line.strip()
        if stripped in SECTION_MARKERS:
            flush_section()
            current_section = SECTION_MARKERS[stripped]
            continue
        if SEPARATOR_RE.match(stripped):
            continue
        if current_section is None and ":" in line and not stripped.startswith("http"):
            key, _, val = line.partition(":")
            meta[key.strip().lower().replace(" ", "_")] = val.strip()
        elif current_section:
            section_buffer.append(line)

    flush_section()

    # Apply Walmart-standard fixed fields — read from team-config.yaml, fall back to built-ins
    snow = _snow_defaults()
    fields["state"] = STATE_DRAFT
    fields["assignment_group"] = snow["assignment_group"]
    fields["u_primary_escalation_group"] = snow["primary_escalation_group"]
    fields["u_secondary_escalation_group"] = snow["secondary_escalation_group"]
    fields["u_change_manager_group"] = snow["change_manager_group"]
    fields["type"] = "normal"
    fields["category"] = "application"
    fields["impact"] = "3"
    fields["u_market"] = snow["market"]
    fields["cmdb_ci"] = snow["cmdb_ci"]
    fields["u_affected_application"] = snow["affected_application"]
    fields["u_ci_class_name"] = "Business Application"
    fields["u_reason_for_install"] = meta.get("reason_for_install", "enhancement")
    fields["u_change_classification"] = "software"
    fields["u_testing_completed"] = "yes"
    fields["u_type_of_testing_completed"] = "technical_testing,functional_testing"
    fields["cab_required"] = "false"

    # Planned dates: next day 15:00 CDT → end day after at 15:00 CDT
    cdt_offset = timedelta(hours=-5)
    now_utc = datetime.now(timezone.utc)
    now_cdt = now_utc + cdt_offset
    next_day_cdt = (now_cdt + timedelta(days=1)).replace(hour=15, minute=0, second=0, microsecond=0)
    end_day_cdt = next_day_cdt + timedelta(days=1)
    fields["start_date"] = (next_day_cdt - cdt_offset).strftime("%Y-%m-%d %H:%M:%S")
    fields["end_date"] = (end_day_cdt - cdt_offset).strftime("%Y-%m-%d %H:%M:%S")

    geo_raw = meta.get("impacted_geos", "CA").strip()
    fields["u_affected_geos"] = geo_raw

    if not fields.get("short_description"):
        fields["short_description"] = path.stem

    return {"fields": fields, "source_file": str(path), "meta_parsed": meta}


def tool_create_crq_draft(args: dict) -> dict:
    """
    POST a new change request in Draft state (state=-5). Never auto-submits.

    Args:
      fields   (dict, required) — ServiceNow field dict (from parse_crq_file or manual)
      dry_run  (bool, default false) — if true, returns fields without POSTing
    """
    fields = args.get("fields")
    if not fields or not isinstance(fields, dict):
        return {"error": "fields dict is required"}

    dry_run = bool(args.get("dry_run", False))

    # Safety: always draft, never allow caller to escalate
    fields["state"] = STATE_DRAFT

    if not fields.get("short_description", "").strip():
        return {"error": "short_description is required in fields"}

    if dry_run:
        return {"dry_run": True, "would_post": fields}

    session = load_session()
    if not session:
        return session_expired_error()

    headers = _build_headers(session)
    status, data, _ = _http("POST", CHANGE_REQUEST_TABLE, headers, body=fields)

    if status is None:
        return {"error": "connection_failed", "detail": str(data)}
    if status == 401:
        return session_expired_error()
    if status not in (200, 201):
        return {"error": f"http_{status}", "detail": str(data)[:1000]}

    result = data.get("result", {})
    crq_number = result.get("number", "?")
    sys_id = result.get("sys_id", "?")
    crq_url = f"{SERVICENOW_BASE}/nav_to.do?uri=change_request.do?sys_id={sys_id}"

    return {
        "status": "created",
        "crq_number": crq_number,
        "sys_id": sys_id,
        "url": crq_url,
        "short_description": result.get("short_description", ""),
        "state": result.get("state", STATE_DRAFT),
        "note": "CRQ is in Draft. Review in ServiceNow before submitting.",
    }


def tool_search_incidents(args: dict) -> dict:
    """
    Search ServiceNow incidents by assignment group and/or state.

    Args:
      assignment_group (str, default "INTL-ET360") — assignment group name
      state            (str, default "active")      — "active", "resolved", "all"
      limit            (int, default 20)             — max records to return
      query            (str, optional)               — additional sysparm_query fragment
    """
    group = args.get("assignment_group", _snow_defaults()["assignment_group"]).strip()
    state_filter = args.get("state", "active").strip().lower()
    limit = int(args.get("limit", 20))
    extra_query = args.get("query", "").strip()

    session = load_session()
    if not session:
        return session_expired_error()

    # Build sysparm_query
    parts = [f"assignment_group.name={group}"]
    if state_filter == "active":
        parts.append("active=true")
    elif state_filter == "resolved":
        parts.append("state=6")  # 6 = Resolved in ServiceNow
    elif state_filter == "open":
        parts.append("state!=6^state!=7")  # exclude Resolved and Closed
    # "all" — no state filter
    if extra_query:
        parts.append(extra_query)

    sysparm_query = "^".join(parts)
    fields = ",".join([
        "number", "sys_id", "short_description", "state", "priority",
        "severity", "assigned_to", "assignment_group", "opened_at",
        "resolved_at", "category", "subcategory", "cmdb_ci",
        "description", "close_notes", "active",
    ])
    path = (
        f"{INCIDENT_TABLE}"
        f"?sysparm_query={sysparm_query}"
        f"&sysparm_limit={limit}"
        f"&sysparm_fields={fields}"
        f"&sysparm_display_value=true"
        f"&sysparm_order_by_direction=desc"
        f"&sysparm_order_by=opened_at"
    )

    headers = _build_headers(session)
    status, data, _ = _http("GET", path, headers)

    if status is None:
        return {"error": "connection_failed", "detail": str(data)}
    if status == 401:
        return session_expired_error()
    if status not in (200, 201):
        return {"error": f"http_{status}", "detail": str(data)[:500]}

    records = data.get("result", [])
    incidents = []
    for r in records:
        inc = {}
        for k, v in r.items():
            inc[k] = v.get("display_value") if isinstance(v, dict) else v
        incidents.append(inc)

    return {
        "assignment_group": group,
        "state_filter": state_filter,
        "count": len(incidents),
        "incidents": incidents,
    }


def tool_get_incident(args: dict) -> dict:
    """
    GET a ServiceNow incident by INC number.

    Args:
      number          (str, required) — e.g. "INC53036685"
      show_all_fields (bool, default false) — return all raw fields
    """
    number = args.get("number", "").strip()
    if not number:
        return {"error": "number is required"}
    show_all = bool(args.get("show_all_fields", False))

    session = load_session()
    if not session:
        return session_expired_error()

    headers = _build_headers(session)
    params = f"sysparm_query=number={number}&sysparm_limit=1&sysparm_display_value=true"
    if not show_all:
        fields = ",".join([
            "number", "sys_id", "short_description", "state", "priority",
            "severity", "assigned_to", "assignment_group", "opened_at",
            "resolved_at", "category", "subcategory", "cmdb_ci",
            "description", "close_notes", "active", "work_notes",
            "caller_id", "impact", "urgency",
        ])
        params += f"&sysparm_fields={fields}"

    path = f"{INCIDENT_TABLE}?{params}"
    status, data, _ = _http("GET", path, headers)

    if status is None:
        return {"error": "connection_failed", "detail": str(data)}
    if status == 401:
        return session_expired_error()
    if status != 200:
        return {"error": f"http_{status}", "detail": str(data)[:500]}

    records = data.get("result", [])
    if not records:
        return {"error": "not_found", "number": number}

    r = records[0]
    incident = {k: (v.get("display_value") if isinstance(v, dict) else v) for k, v in r.items()}
    return {"incident": incident}


def tool_get_my_ritm_approvals(args: dict) -> dict:
    """
    Get ServiceNow RITM (Requested Item) approvals pending for the current user.

    Queries sysapproval_approver where approver = current user AND state = requested,
    then enriches with RITM details (short_description, requested_for, cat_item).

    Args:
      include_all_types (bool, default false) — include non-RITM approvals too (CHG, CAP, etc.)
      limit             (int, default 50)     — max approval records to return
    """
    include_all = bool(args.get("include_all_types", False))
    limit = int(args.get("limit", 50))

    session = load_session()
    if not session:
        return session_expired_error()

    headers = _build_headers(session)

    # Step 1: get current user's sys_id
    status, data, _ = _http("GET", "/api/now/ui/user/current_user", headers)
    if status is None:
        return {"error": "connection_failed", "detail": str(data)}
    if status == 401:
        return session_expired_error()
    if status != 200:
        return {"error": f"http_{status}_on_current_user", "detail": str(data)[:300]}

    user_info = data.get("result", {})
    user_sys_id = user_info.get("user_sys_id", "")
    user_name = user_info.get("user_display_name", user_info.get("user_name", "unknown"))
    if not user_sys_id:
        return {"error": "could_not_resolve_user_sys_id", "raw": user_info}

    # Step 2: fetch pending approvals
    path = (
        "/api/now/table/sysapproval_approver"
        f"?sysparm_query=approver={user_sys_id}^state=requested"
        "&sysparm_display_value=true"
        f"&sysparm_limit={limit}"
        "&sysparm_fields=sys_id,state,approver,source_table,sysapproval,document_id,created_on,due_date,comments"
    )
    status, data, _ = _http("GET", path, headers)
    if status is None:
        return {"error": "connection_failed", "detail": str(data)}
    if status == 401:
        return session_expired_error()
    if status != 200:
        return {"error": f"http_{status}", "detail": str(data)[:500]}

    approvals_raw = data.get("result", [])

    def _flat(r):
        return {k: (v.get("display_value") if isinstance(v, dict) else v) for k, v in r.items()}

    all_approvals = [_flat(r) for r in approvals_raw]

    # Filter to RITM only unless include_all_types=True
    ritm_approvals = [a for a in all_approvals if a.get("source_table") == "sc_req_item"]
    other_approvals = [a for a in all_approvals if a.get("source_table") != "sc_req_item"]

    # Step 3: enrich RITM approvals with RITM details
    ritm_numbers = [a["sysapproval"] for a in ritm_approvals if a.get("sysapproval")]
    ritm_detail_map = {}
    if ritm_numbers:
        nums_query = "^ORnumber=".join(ritm_numbers)
        detail_path = (
            "/api/now/table/sc_req_item"
            f"?sysparm_query=number={nums_query}"
            "&sysparm_display_value=true"
            f"&sysparm_limit={len(ritm_numbers)}"
            "&sysparm_fields=number,short_description,state,requested_for,opened_by,cat_item,opened_at,request"
        )
        d_status, d_data, _ = _http("GET", detail_path, headers)
        if d_status == 200:
            for r in d_data.get("result", []):
                flat = _flat(r)
                ritm_detail_map[flat.get("number", "")] = flat

    # Merge
    enriched = []
    for a in ritm_approvals:
        ritm_num = a.get("sysapproval", "")
        detail = ritm_detail_map.get(ritm_num, {})
        enriched.append({
            "ritm_number":     ritm_num,
            "approval_state":  a.get("state"),
            "approval_due":    a.get("due_date"),
            "approval_sys_id": a.get("sys_id"),
            "cat_item":        detail.get("cat_item", ""),
            "short_description": detail.get("short_description", a.get("document_id", "")),
            "ritm_state":      detail.get("state", ""),
            "requested_for":   detail.get("requested_for", ""),
            "opened_by":       detail.get("opened_by", ""),
            "opened_at":       detail.get("opened_at", ""),
            "parent_request":  detail.get("request", ""),
        })

    result = {
        "user": user_name,
        "user_sys_id": user_sys_id,
        "ritm_approvals_count": len(enriched),
        "ritm_approvals": enriched,
    }

    if include_all:
        result["other_approvals_count"] = len(other_approvals)
        result["other_approvals"] = other_approvals

    return result


# ── MCP dispatcher ────────────────────────────────────────────────────────────
TOOLS = {
    "get_crq": {
        "fn": tool_get_crq,
        "description": "GET a ServiceNow change request by CHG number",
        "inputSchema": {
            "type": "object",
            "properties": {
                "number": {"type": "string", "description": "CRQ number e.g. CHG3978198"},
                "show_all_fields": {"type": "boolean", "description": "Return all raw fields (for field discovery)"},
            },
            "required": ["number"],
        },
    },
    "parse_crq_file": {
        "fn": tool_parse_crq_file,
        "description": "Parse a .txt CRQ file (from /crq-generator) into ServiceNow fields ready for create_crq_draft",
        "inputSchema": {
            "type": "object",
            "properties": {
                "path": {"type": "string", "description": "Path to .txt CRQ file (~ expansion supported)"},
            },
            "required": ["path"],
        },
    },
    "create_crq_draft": {
        "fn": tool_create_crq_draft,
        "description": "POST a new ServiceNow change request in Draft state. Never auto-submits.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "fields": {"type": "object", "description": "ServiceNow field dict (from parse_crq_file or manual)"},
                "dry_run": {"type": "boolean", "description": "If true, return fields without POSTing"},
            },
            "required": ["fields"],
        },
    },
    "search_incidents": {
        "fn": tool_search_incidents,
        "description": "Search ServiceNow incidents by assignment group and state. Returns structured list with display names (not GUIDs). Default group: INTL-ET360.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "assignment_group": {"type": "string", "description": "Assignment group name (default: INTL-ET360)"},
                "state":            {"type": "string", "description": "Filter: 'active' (default), 'resolved', 'open', 'all'"},
                "limit":            {"type": "integer", "description": "Max records to return (default 20)"},
                "query":            {"type": "string", "description": "Extra sysparm_query fragment e.g. 'priority=1'"},
            },
        },
    },
    "get_incident": {
        "fn": tool_get_incident,
        "description": "GET a ServiceNow incident by INC number. Returns full details with display names.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "number":          {"type": "string",  "description": "Incident number e.g. INC53036685"},
                "show_all_fields": {"type": "boolean", "description": "Return all raw fields (for field discovery)"},
            },
            "required": ["number"],
        },
    },
    "get_my_ritm_approvals": {
        "fn": tool_get_my_ritm_approvals,
        "description": (
            "Get ServiceNow RITM (Requested Item) approvals pending for the current user. "
            "Queries sysapproval_approver table filtered to current user + state=requested, "
            "then enriches with RITM short_description, requested_for, cat_item."
        ),
        "inputSchema": {
            "type": "object",
            "properties": {
                "include_all_types": {"type": "boolean", "description": "Include non-RITM approvals too (CHG, CAP, etc.) — default false"},
                "limit":             {"type": "integer", "description": "Max approval records to return (default 50)"},
            },
        },
    },
}


def handle_request(req: dict) -> dict:
    method = req.get("method", "")
    req_id = req.get("id")

    def ok(result):
        return {"jsonrpc": "2.0", "id": req_id, "result": result}

    def err(code, message):
        return {"jsonrpc": "2.0", "id": req_id, "error": {"code": code, "message": message}}

    if method == "initialize":
        return ok({
            "protocolVersion": "2024-11-05",
            "capabilities": {"tools": {}},
            "serverInfo": {"name": "sarthi-snow", "version": "1.0.0"},
        })

    if method == "notifications/initialized":
        return None

    if method == "tools/list":
        tools_list = []
        for name, spec in TOOLS.items():
            tools_list.append({
                "name": name,
                "description": spec["description"],
                "inputSchema": spec["inputSchema"],
            })
        return ok({"tools": tools_list})

    if method == "tools/call":
        params = req.get("params", {})
        tool_name = params.get("name", "")
        tool_args = params.get("arguments", {})
        if tool_name not in TOOLS:
            return err(-32601, f"Unknown tool: {tool_name}")
        try:
            result = TOOLS[tool_name]["fn"](tool_args)
            return ok({"content": [{"type": "text", "text": json.dumps(result, indent=2)}]})
        except Exception as e:
            log(f"ERROR in {tool_name}: {e}")
            return err(-32603, str(e))

    if method == "ping":
        return ok({})

    return err(-32601, f"Method not found: {method}")


def run_stdio():
    log("sarthi-snow MCP server starting (stdio)")
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            req = json.loads(line)
        except json.JSONDecodeError as e:
            log(f"WARN: invalid JSON: {e}")
            continue
        resp = handle_request(req)
        if resp is not None:
            sys.stdout.write(json.dumps(resp) + "\n")
            sys.stdout.flush()


def run_test(tool_name: str, args_json: str):
    """CLI test mode: python3 server.py --test <tool> '<json args>'"""
    if tool_name not in TOOLS:
        print(f"Unknown tool: {tool_name}")
        print(f"Available: {', '.join(TOOLS.keys())}")
        sys.exit(1)
    try:
        args = json.loads(args_json) if args_json else {}
    except json.JSONDecodeError as e:
        print(f"Invalid JSON args: {e}")
        sys.exit(1)
    result = TOOLS[tool_name]["fn"](args)
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="sarthi-snow MCP server")
    parser.add_argument("--test", metavar="TOOL", help="Run a single tool and print result")
    parser.add_argument("args_json", nargs="?", default="{}", help="JSON args for --test mode")
    parsed = parser.parse_args()

    if parsed.test:
        run_test(parsed.test, parsed.args_json)
    else:
        run_stdio()
