#!/usr/bin/env python3
"""
snow_client.py — ServiceNow REST API client for CRQ management.

Uses session cookie from ~/.wibey/snow-session.json (generated by extract_snow_session.py)
to interact with ServiceNow change_request table.

Usage:
    # Discover field names from existing CRQ
    python3 snow_client.py get CHG3978198

    # Create a CRQ draft from a .txt file
    python3 snow_client.py create ~/.wibey/knowledge/crqs/2026-05-04-id-50183-lmd-filter.txt

    # Create a CRQ draft from inline JSON
    python3 snow_client.py create --json '{"short_description": "test"}'
"""

import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    import requests
    from requests.packages.urllib3.exceptions import InsecureRequestWarning
    requests.packages.urllib3.disable_warnings(InsecureRequestWarning)
except ImportError:
    print("❌ requests not installed. Run: pip install requests")
    sys.exit(1)

SERVICENOW_BASE = "https://walmartglobal.service-now.com"
CHANGE_REQUEST_TABLE = "/api/now/table/change_request"
SESSION_FILE = Path.home() / ".wibey" / "snow-session.json"

# ── Field mapping: CRQ txt format → ServiceNow API field names ───────────────
# These are discovered from GET /api/now/table/change_request?sysparm_limit=1
# Standard ITSM fields + Walmart custom fields (u_ prefix)
FIELD_MAP = {
    # Standard ServiceNow fields
    "short_description": "short_description",
    "description": "description",
    "risk": "risk",
    "impact": "impact",
    "type": "type",
    "category": "category",
    "state": "state",
    # Walmart custom fields (discovered from existing CRQs)
    "change_owner_group": "assignment_group",
    "impacted_geos": "u_impacted_geo",
    "business_unit": "u_business_unit",
    "reason_for_install": "u_reason_for_install",
    "affected_application": "u_affected_application",
    "primary_ci": "cmdb_ci",
    "dr_tier": "u_dr_tier",
    "change_classification": "u_change_classification",
    "has_testing_completed": "u_has_testing_completed",
    "type_of_testing": "u_type_of_testing",
    "implementation_plan": "u_implementation_plan",
    "validation_plan": "u_validation_plan",
    "backout_plan": "u_backout_plan",
    "cab_required": "cab_required",
}

# Risk value mapping (ServiceNow uses numeric codes)
RISK_VALUES = {
    "low": "3",
    "moderate": "2",
    "medium": "2",
    "high": "1",
}

# State codes
STATE_DRAFT = "-5"   # New/Draft — safe default
STATE_ASSESS = "-4"  # Assess


def load_session() -> dict:
    """Load session from ~/.wibey/snow-session.json."""
    if not SESSION_FILE.exists():
        print(f"❌ No session file at {SESSION_FILE}")
        print("   Run: python3 extract_snow_session.py")
        sys.exit(1)

    with open(SESSION_FILE) as f:
        session = json.load(f)

    extracted_at = session.get("extracted_at", "unknown")
    print(f"  🍪 Session loaded (extracted: {extracted_at})")
    return session


def get_user_token(session: dict) -> str:
    """
    ServiceNow REST API requires X-UserToken which is returned in the response
    headers of any request. Do a lightweight HEAD-like GET to fetch it.
    The token is returned as X-UserToken-Response header.
    """
    # Use cached token if present
    if session.get("x_user_token"):
        return session["x_user_token"]

    url = f"{SERVICENOW_BASE}{CHANGE_REQUEST_TABLE}"
    headers = {
        "Cookie": session["cookie_header"],
        "Accept": "application/json",
    }
    # Fetch just 1 field to get the token from response headers
    resp = requests.get(
        url,
        headers=headers,
        params={"sysparm_limit": 1, "sysparm_fields": "number"},
        verify=False,
        timeout=15,
    )
    token = resp.headers.get("X-UserToken-Response", "")
    if not token:
        print("  ⚠️  Could not obtain X-UserToken-Response header")
    else:
        print(f"  🔑 X-UserToken obtained ({token[:20]}...)")
        session["x_user_token"] = token  # cache for this session
    return token


def build_headers(session: dict) -> dict:
    """Build HTTP headers with session cookie and X-UserToken."""
    token = get_user_token(session)
    return {
        "Cookie": session["cookie_header"],
        "Content-Type": "application/json",
        "Accept": "application/json",
        "X-UserToken": token,
    }


def get_crq(number: str, session: dict = None, show_all_fields: bool = False) -> dict:
    """
    GET a change request by number.
    Use show_all_fields=True to discover all available field names.
    """
    if session is None:
        session = load_session()

    headers = build_headers(session)
    params = {
        "sysparm_query": f"number={number}",
        "sysparm_limit": 1,
    }
    if show_all_fields:
        params["sysparm_fields"] = ""  # empty = all fields

    url = f"{SERVICENOW_BASE}{CHANGE_REQUEST_TABLE}"
    print(f"  🔍 GET {url} (number={number})")

    resp = requests.get(url, headers=headers, params=params, verify=False, timeout=30)

    if resp.status_code == 401:
        print("  ❌ 401 Unauthorized — session cookie may have expired.")
        print("     Run: python3 extract_snow_session.py")
        sys.exit(1)

    if resp.status_code != 200:
        print(f"  ❌ HTTP {resp.status_code}: {resp.text[:500]}")
        sys.exit(1)

    data = resp.json()
    records = data.get("result", [])

    if not records:
        print(f"  ❌ No CRQ found with number: {number}")
        sys.exit(1)

    record = records[0]
    print(f"  ✅ Found: {record.get('number', '?')} — {record.get('short_description', '?')[:80]}")
    return record


def print_crq_fields(record: dict):
    """Pretty-print CRQ fields for discovery."""
    print("\n" + "=" * 70)
    print(f"CRQ Field Discovery: {record.get('number', '?')}")
    print("=" * 70)

    # Key fields first
    key_fields = [
        "number", "short_description", "state", "risk", "impact",
        "type", "category", "assignment_group", "cmdb_ci",
        "cab_required", "description",
    ]
    print("\n── Key Fields ──")
    for f in key_fields:
        val = record.get(f, "")
        if isinstance(val, dict):
            val = val.get("display_value", val.get("value", ""))
        if val:
            print(f"  {f:35s} = {str(val)[:80]}")

    # Walmart custom fields (u_ prefix)
    print("\n── Walmart Custom Fields (u_*) ──")
    for k, v in sorted(record.items()):
        if k.startswith("u_"):
            val = v if not isinstance(v, dict) else v.get("display_value", v.get("value", ""))
            if val:
                print(f"  {k:35s} = {str(val)[:80]}")

    print("=" * 70)


def parse_crq_txt(txt_path: str) -> dict:
    """
    Parse a CRQ .txt file (generated by /crq-generator) into ServiceNow fields.
    Returns a dict ready to POST.
    """
    path = Path(txt_path).expanduser()
    if not path.exists():
        print(f"❌ File not found: {txt_path}")
        sys.exit(1)

    text = path.read_text()
    lines = text.splitlines()

    fields = {}
    current_section = None
    section_buffer = []

    def flush_section():
        nonlocal section_buffer
        content = "\n".join(section_buffer).strip()
        if current_section == "summary":
            fields["short_description"] = content
        elif current_section == "description":
            fields["description"] = content
        elif current_section == "implementation":
            fields["implementation_plan"] = content
        elif current_section == "validation":
            fields["test_plan"] = content
        elif current_section == "backout":
            fields["backout_plan"] = content
        section_buffer = []

    SECTION_MARKERS = {
        "Summary": "summary",
        "Description": "description",
        "Implementation plan": "implementation",
        "Validation plan": "validation",
        "Backout plan": "backout",
    }
    SEPARATOR = "─" * 10  # partial match

    for line in lines:
        # Check for section header (line after separator)
        stripped = line.strip()
        if stripped in SECTION_MARKERS:
            flush_section()
            current_section = SECTION_MARKERS[stripped]
            continue

        if SEPARATOR in stripped:
            continue

        # Parse header key-value fields (before first section)
        if current_section is None and ":" in line and not stripped.startswith("http"):
            key, _, val = line.partition(":")
            val = val.strip()
            key = key.strip().lower().replace(" ", "_")
            fields[f"_meta_{key}"] = val
        elif current_section:
            section_buffer.append(line)

    flush_section()

    # risk is auto-calculated by ServiceNow ML — do not set manually

    # State = Draft (never auto-submit)
    fields["state"] = STATE_DRAFT

    # Fixed fields matching CHG3978198 reference CRQ
    fields["assignment_group"] = "INTL-ET360"
    fields["u_primary_escalation_group"] = "INTL-ET360"
    fields["u_secondary_escalation_group"] = "INTL-ET360"
    fields["u_change_manager_group"] = "Change Managers - US"
    fields["type"] = "normal"
    fields["category"] = "application"
    fields["impact"] = "3"  # 3 = Moderate (verified from CHG3978198)
    fields["u_market"] = "Home Office"
    fields["cmdb_ci"] = "International Datalake"
    fields["u_affected_application"] = "International Datalake"
    fields["u_ci_class_name"] = "Business Application"
    fields["u_reason_for_install"] = fields.get("_meta_reason_for_install", "enhancement")
    fields["u_change_classification"] = "software"
    fields["u_testing_completed"] = "yes"
    fields["u_type_of_testing_completed"] = "technical_testing,functional_testing"
    fields["cab_required"] = "false"

    # Planned dates: next calendar day at 15:00 CDT (20:00 UTC), end = day after at 15:00 CDT
    # ServiceNow date format: YYYY-MM-DD HH:MM:SS (verified from CHG4008143)
    from datetime import datetime, timedelta, timezone
    now_utc = datetime.now(timezone.utc)
    # CDT = UTC-5 (May). Next day 3PM CDT = 20:00 UTC
    cdt_offset = timedelta(hours=-5)
    now_cdt = now_utc + cdt_offset
    next_day_cdt = (now_cdt + timedelta(days=1)).replace(hour=15, minute=0, second=0, microsecond=0)
    end_day_cdt = next_day_cdt + timedelta(days=1)
    # Convert to UTC for ServiceNow storage
    next_day_utc = next_day_cdt - cdt_offset
    end_day_utc = end_day_cdt - cdt_offset
    fields["start_date"] = next_day_utc.strftime("%Y-%m-%d %H:%M:%S")
    fields["end_date"] = end_day_utc.strftime("%Y-%m-%d %H:%M:%S")

    # GEO: extract from _meta (CA, MX, or CA + MX)
    geo_raw = fields.get("_meta_impacted_geos", "CA").strip()
    fields["u_affected_geos"] = geo_raw

    # u_vp_approval and risk are auto-populated by ServiceNow based on assignment_group and ML model
    # Do NOT hardcode — let ServiceNow derive them

    # Short description fallback
    if not fields.get("short_description"):
        fields["short_description"] = path.stem

    # Clean up meta keys
    fields = {k: v for k, v in fields.items() if not k.startswith("_meta_")}

    return fields


def create_crq_draft(fields: dict, session: dict = None, dry_run: bool = False) -> dict:
    """
    POST a new change request in Draft state.
    Always uses state=-5 (Draft) regardless of input.
    """
    if session is None:
        session = load_session()

    # Safety: always draft
    fields["state"] = STATE_DRAFT

    # Required fields check
    if not fields.get("short_description"):
        print("❌ short_description is required")
        sys.exit(1)

    if dry_run:
        print("\n🔵 DRY RUN — would POST these fields:")
        for k, v in sorted(fields.items()):
            print(f"  {k:35s} = {str(v)[:80]}")
        return {}

    headers = build_headers(session)
    url = f"{SERVICENOW_BASE}{CHANGE_REQUEST_TABLE}"

    print(f"\n  📤 POST {url}")
    print(f"  📋 short_description: {fields.get('short_description', '')[:80]}")
    print(f"  📋 state: {fields.get('state')} (Draft)")

    resp = requests.post(url, headers=headers, json=fields, verify=False, timeout=30)

    if resp.status_code == 401:
        print("  ❌ 401 Unauthorized — session cookie expired.")
        print("     Run: python3 extract_snow_session.py")
        sys.exit(1)

    if resp.status_code not in (200, 201):
        print(f"  ❌ HTTP {resp.status_code}: {resp.text[:1000]}")
        sys.exit(1)

    result = resp.json().get("result", {})
    crq_number = result.get("number", "?")
    sys_id = result.get("sys_id", "?")
    crq_url = f"{SERVICENOW_BASE}/nav_to.do?uri=change_request.do?sys_id={sys_id}"

    print(f"\n  ✅ CRQ created: {crq_number}")
    print(f"  🔗 URL: {crq_url}")

    return result


def add_approver_via_browser(
    crq_sys_id: str,
    approver_user_id: str = "s0s07p0",
    approver_sys_id: str = "54daa76ddb54cc50ba9f3c9d7c96191d",
    approver_display_name: str = "Swaroop YS",
) -> bool:
    """
    Adds a manual approver to a CRQ via browser automation (agent-browser).

    Flow (JS-based, inline slushbucket dialog):
      1. Open CRQ via nav_to URL
      2. Click "Add Change Approvers" button by text match
      3. Click the reflistOpen anchor (magnifier) to open user search popup
      4. In popup: select "User ID" field, type approver_user_id, press Enter
      5. Click the matching user button (matched by sys_id in onclick)
      6. Click OK to confirm

    Returns True on success, False on failure.

    Verified deterministic on 2026-05-11 (CHG4021535, s0s07p0 = Swaroop YS).
    Button ID bed909a197d331502b67f35de053aff1 is a static ServiceNow UI element.
    Swaroop YS sys_id = 54daa76ddb54cc50ba9f3c9d7c96191d.
    """
    import subprocess
    import time

    WRAPPER = str(Path.home() / ".wibey" / "skills" / "agent-browser" / "scripts" / "agent-browser-wrapper.sh")
    crq_url = f"{SERVICENOW_BASE}/nav_to.do?uri=change_request.do?sys_id={crq_sys_id}"

    def ab(*args, timeout: int = 30) -> tuple[int, str]:
        """Run an agent-browser-wrapper command, return (returncode, stdout)."""
        result = subprocess.run(
            ["bash", WRAPPER] + list(args),
            capture_output=True, text=True, timeout=timeout
        )
        return result.returncode, result.stdout.strip()

    def ab_eval(js: str, timeout: int = 30) -> tuple[int, str]:
        """Run agent-browser eval with a JS snippet."""
        result = subprocess.run(
            ["bash", WRAPPER, "eval", js],
            capture_output=True, text=True, timeout=timeout
        )
        return result.returncode, result.stdout.strip()

    print(f"\n  🌐 Opening CRQ in browser to add approver ({approver_user_id})...")

    # Step 1: navigate to CRQ
    rc, out = ab("open", crq_url)
    if rc != 0:
        print(f"  ❌ Failed to open browser: {out}")
        return False

    # Wait for the page iframe to load (check for 'Load Related Lists' button)
    js_wait_page = """
const frame = window.frames[0];
if (!frame || !frame.document) { 'loading'; }
else {
  const btn = Array.from(frame.document.querySelectorAll('button'))
    .find(b => b.textContent.trim() === 'Load Related Lists' || b.textContent.trim() === 'Add Change Approvers');
  btn ? 'ready' : 'loading';
}
"""
    for attempt in range(20):  # up to 20s
        time.sleep(1)
        rc, out = ab_eval(js_wait_page)
        if '"ready"' in out:
            break
    else:
        print(f"  ❌ Timed out waiting for page to load")
        return False

    # Click "Load Related Lists" to reveal the Approvers section (if present)
    js_load_related = """
const frame = window.frames[0];
const btn = Array.from(frame.document.querySelectorAll('button'))
  .find(b => b.textContent.trim() === 'Load Related Lists');
if (btn) { btn.click(); 'clicked'; } else { 'already_loaded'; }
"""
    rc, out = ab_eval(js_load_related)
    if '"clicked"' in out:
        time.sleep(4)  # wait for related lists to render

    # Now wait for Add Change Approvers button
    js_wait_approver = """
const frame = window.frames[0];
const btn = Array.from(frame.document.querySelectorAll('button'))
  .find(b => b.textContent.trim() === 'Add Change Approvers');
btn ? 'ready' : 'loading';
"""
    for attempt in range(10):  # up to 10s
        time.sleep(1)
        rc, out = ab_eval(js_wait_approver)
        if '"ready"' in out:
            break
    else:
        print(f"  ❌ Timed out waiting for Add Change Approvers button")
        return False

    # Step 2: click "Add Change Approvers" button — opens an inline slushbucket dialog
    # The dialog id is 'approvers' and is rendered inside window.frames[0]
    js_click_btn = """
const frame = window.frames[0];
const btn = Array.from(frame.document.querySelectorAll('button'))
  .find(b => b.textContent.trim() === 'Add Change Approvers');
if (!btn) throw new Error('Add Change Approvers button not found');
btn.scrollIntoView();
btn.click();
'ok';
"""
    rc, out = ab_eval(js_click_btn)
    if rc != 0 or '"ok"' not in out:
        print(f"  ❌ Could not click 'Add Change Approvers': {out}")
        return False
    time.sleep(2)

    # Step 3: wait for approvers dialog to appear
    js_wait_dialog = """
const frame = window.frames[0];
const dlg = frame.document.getElementById('approvers');
(dlg && dlg.style.display !== 'none' && dlg.querySelector('select[id^=\"select_0\"]')) ? 'ready' : 'loading';
"""
    for attempt in range(10):
        time.sleep(1)
        rc, out = ab_eval(js_wait_dialog)
        if '"ready"' in out:
            break
    else:
        print(f"  ❌ Timed out waiting for approvers dialog")
        return False

    # Step 4: add approver to the slushbucket select and set selected_users hidden field
    # The dialog uses a slushbucket widget — we add an <option> directly to the select,
    # call synchLists to sync the hidden field, then submit.
    # Verified 2026-05-29: inline dialog, NOT a popup window.
    # approver_sys_id must be the sys_user sys_id (not user_name).
    js_add_user = f"""
const frame = window.frames[0];
const dlg = frame.document.getElementById('approvers');
const sel = dlg.querySelector('select[id^="select_0"]');
const option = frame.document.createElement('option');
option.value = '{approver_sys_id}';
option.text = '{approver_display_name}';
option.selected = true;
sel.appendChild(option);
for (let o of sel.options) o.selected = true;
const queryKey = sel.id.replace('select_0', '');
if (frame.synchLists) frame.synchLists(queryKey);
const hidden = dlg.querySelector('#selected_users');
if (hidden) hidden.value = '{approver_sys_id}';
'added';
"""
    rc, out = ab_eval(js_add_user)
    if rc != 0 or '"added"' not in out:
        print(f"  ❌ Could not add user to slushbucket: {out}")
        return False

    # Step 5: click OK to submit the form
    js_click_ok = """
const frame = window.frames[0];
const ok = frame.document.getElementById('subbed_ok_btn');
if (!ok) throw new Error('OK button not found');
for (let o of frame.document.querySelectorAll('select[id^="select_0"] option')) o.selected = true;
ok.click();
'ok';
"""
    rc, out = ab_eval(js_click_ok)
    if rc != 0 or '"ok"' not in out:
        print(f"  ❌ Could not click OK: {out}")
        return False
    time.sleep(3)

    print(f"  ✅ Swaroop YS ({approver_user_id}) added as approver")
    return True


# Keep old name as alias for backward compatibility
def add_manual_approver(crq_sys_id: str, approver_user_sys_id: str, session: dict = None) -> dict:
    """Wrapper: calls add_approver_via_browser. approver_user_sys_id arg ignored (kept for compat)."""
    add_approver_via_browser(crq_sys_id)
    return {}


# Default Swaroop YS sys_id (verified 2026-05-11 from CHG3978198)
SWAROOP_YS_USER_SYS_ID = "54daa76ddb54cc50ba9f3c9d7c96191d"


def main():
    import argparse

    parser = argparse.ArgumentParser(description="ServiceNow CRQ REST client")
    subparsers = parser.add_subparsers(dest="command")

    # get command
    get_parser = subparsers.add_parser("get", help="GET a CRQ by number")
    get_parser.add_argument("number", help="CRQ number (e.g. CHG3978198)")
    get_parser.add_argument("--all-fields", action="store_true", help="Show all fields")

    # create command
    create_parser = subparsers.add_parser("create", help="Create a CRQ draft")
    create_parser.add_argument("source", nargs="?", help="Path to .txt CRQ file")
    create_parser.add_argument("--json", help="JSON string of fields")
    create_parser.add_argument("--dry-run", action="store_true", help="Print fields without POSTing")
    create_parser.add_argument("--no-approver", action="store_true",
                               help="Skip adding Swaroop YS as manual approver")

    # discover command
    discover_parser = subparsers.add_parser("discover", help="Discover field names from existing CRQ")
    discover_parser.add_argument("number", nargs="?", default="CHG3978198", help="CRQ number to inspect")

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        sys.exit(0)

    print("=" * 60)
    print("🏥 ServiceNow CRQ Client")
    print("=" * 60)

    session = load_session()

    if args.command == "get":
        record = get_crq(args.number, session, show_all_fields=args.all_fields)
        print_crq_fields(record)

    elif args.command == "discover":
        print(f"\n  Fetching all fields from {args.number} to discover field names...")
        record = get_crq(args.number, session, show_all_fields=True)
        print_crq_fields(record)
        # Save raw to file for reference
        out = Path.home() / ".wibey" / "snow-field-discovery.json"
        with open(out, "w") as f:
            json.dump(record, f, indent=2)
        print(f"\n  💾 Full field data saved to: {out}")

    elif args.command == "create":
        if args.json:
            fields = json.loads(args.json)
        elif args.source:
            print(f"\n  📄 Parsing CRQ file: {args.source}")
            fields = parse_crq_txt(args.source)
            print(f"  📋 Fields extracted: {list(fields.keys())}")
        else:
            print("❌ Provide a .txt file path or --json fields")
            sys.exit(1)

        result = create_crq_draft(fields, session, dry_run=args.dry_run)

        if result and not args.dry_run:
            # Add Swaroop YS as manual approver (default, skip with --no-approver)
            if not getattr(args, 'no_approver', False):
                crq_sys_id = result.get("sys_id", "")
                if crq_sys_id:
                    add_manual_approver(crq_sys_id, SWAROOP_YS_USER_SYS_ID, session)
                else:
                    print("  ⚠️  No sys_id in result — cannot add manual approver")

            # Update crq-index.json if source file matches
            if args.source:
                _update_crq_index(args.source, result)

    else:
        parser.print_help()


def _update_crq_index(source_path: str, snow_result: dict):
    """Update crq-index.json with the ServiceNow CHG number."""
    index_path = Path.home() / ".wibey" / "knowledge" / "crq-index.json"
    if not index_path.exists():
        return

    crq_number = snow_result.get("number", "")
    if not crq_number:
        return

    with open(index_path) as f:
        index = json.load(f)

    source_stem = Path(source_path).expanduser().stem
    for entry in index.get("crqs", []):
        crq_file = entry.get("crq_file", "")
        if source_stem in crq_file:
            entry["crq_number"] = crq_number
            entry["status"] = "SUBMITTED"
            entry["submitted_at"] = datetime.now(timezone.utc).isoformat()
            entry["snow_sys_id"] = snow_result.get("sys_id", "")
            break

    with open(index_path, "w") as f:
        json.dump(index, f, indent=2)

    print(f"  📝 crq-index.json updated with {crq_number}")


if __name__ == "__main__":
    main()
